### ISSUE TITLE
[Bug] README will not update to Step 3 if feature branch was branched from release-v1.0

### ISSUE THREAD

**Issue by davepvelasco** [skills/release-based-workflow#11]
**Describe the bug**
On step 2, the learner is instructed to create a new feature branch, create a pull request, and then merge it into the `release-v1.0` branch. If the learner creates the feature branch from the `release-v1.0` branch, the `on feature added` job in Check Step 2 workflow will be skipped and will fail to update the README to step 3. I think this happens because `.github/scripts/STEP` is still set to 0 on the newly created branch. This does not happen when you branch from `main`.

**To Reproduce**
1. Follow Step 1 and wait for Actions to update the README to Step 2.
2. Switch to `release-v1.0` branch.
![image](https://user-images.githubusercontent.com/113425774/194384255-3e2e7763-0433-4777-8f05-cf024ec47da8.png)
3. Create new branch.
![image](https://user-images.githubusercontent.com/113425774/194384705-eae3172c-f178-47ed-b72d-3929acde9bb6.png)
4. Follow the rest of Step 2 starting from **Activity: Update base.css**

**Expected behavior**
The README should update to STEP 3, but if you followed the steps above, it will not.

**Screenshots**

![image](https://user-images.githubusercontent.com/113425774/194385870-f90ddd56-7c83-4f14-a86d-8b3a81e292f7.png)

**Additional context**
I am not sure if this is the intended process, but a line in STEP 2, specifically:

> In this exercise, you'll use the `release-v1.0` branch to be your one long-lived branch per release version.

might make beginners or non-native speakers think that they should be on the `release-v1.0` branch when they create a new branch as instructed in the next activity.

If that is not the case, then maybe STEP 2 should clarify that you should be branching off from the `main` branch. But then, should it matter that the feature branch must be branched from `main`? Is that what the learner should understand from this guide?

**Comment by sinsukehlab** [comment]
I opened a PR #9 in September, 2022, but it has not been merged yet. :grimacing:
This issue has been resolved in PR #38.

**Comment by heiskr** [comment]
Thank you for opening this issue. Looks like this was addressed in https://github.com/skills/release-based-workflow/issues/37. Let us know if you continue to experience issues.
