### ISSUE TITLE
[Bug] hotfix-v1.0.1 and fix-game-background branches are missing in step 6

### ISSUE THREAD

**Issue by Lerking** [skills/release-based-workflow#37]
Hi,

I'm going through this guide to learn more about the github workflows.
Everything is working until step 6.
It's stated that both hotfix-v1.0.1 and fix-gam-background branches are prepared.
However they are not!
Thereby steps 6 and 7 can't be finalized.

FYI
It's a great guide and lots of valuable information is being presented in an easy to follow way.

/Lerking

**Comment by Lerking** [comment]
These are the branches created on the initial repository creation.
![image](https://user-images.githubusercontent.com/33354709/220597942-7f7c2b64-d0d7-464c-80fc-82fd55ed6799.png)

**Comment by rsese** [comment]
👋 !  I recently updated the course and tested that it works, I'll go through it again to see if I can reproduce the problem you're seeing...

**Comment by rsese** [comment]
hmm I ran through the course again and was able to complete it with no problems -- are you able to reproduce the issue if you run through the course again?

**Comment by Lerking** [comment]
I've just tried running it again from scratch. This time on my Linux system - the first run was on a Windows machine.
However the result was the exact same. 
After finalizing step 5, I only have these branches.
![image](https://user-images.githubusercontent.com/33354709/220774008-e9d97925-e9f3-47fa-941b-b6c82cbef83b.png)

The hotfix-v1.0.1 and fix-game-background branches don't exist and i'm stuck at step 6.

**Comment by rsese** [comment]
ahhh ok I think I see what happened -- I took a peek since your repo is public, I think the problem was at step 2:

https://github.com/Lerking/test-release-based-workflow/pull/2

if you go through the course 1 one more time, at step 2 we should probably be more specific for this bit:


> ### :keyboard: Activity: Update `base.css`
> 
> 1. Create a new branch and change the `body` CSS declaration in `base.css` to match what is below. This will set the page background to black
> 

when you get to this part and create a new branch, can you make sure that you're branching off of `main` and not `release-v1.0`?   This will make sure that the mechanism we use to keep track of which step you're on is updated correctly.

E.g.:

> ### :keyboard: Activity: Update `base.css`
> 
> 1. Create a new branch off of the `main` branch and change the `body` CSS declaration in `base.css` to match what is below. This will set the page background to black
>

**Comment by Lerking** [comment]
I've now run the guide from scratch again. This time making sure to branch of 'main', in step 2!
The problem persists. I can see that a new branch have been added 'rsese-37-explicit-branching', but still the 2 branches in question for step 6 are not there.
![image](https://user-images.githubusercontent.com/33354709/220841941-bb1d8704-a6c8-4555-9236-85864d6f0a70.png)
Could there perhaps be some prerequisites that are needed?

**Comment by Lerking** [comment]
I managed to finish the course.
I agree on your solution to be a bit more specific in step 2 regarding which branch to use as base.
Thank you for you help and thanks for a great tutorial on github workflows.

**Comment by rsese** [comment]
ahh great!  sorry again for the friction here but glad you were able to finish the course 🙌 

> I agree on your solution to be a bit more specific in step 2 regarding which branch to use as base.

will open a PR to clarify what we talked about above 👍

**Comment by sinsukehlab** [comment]
Duplicate of #11
