### ISSUE TITLE
README/Instructions not advancing after completing step 2

### ISSUE THREAD

**Issue by m-den-01A** [skills/release-based-workflow#47]
### Summary

After completing **Create a release based workflow**, the README/instructions did not advance.

### How to reproduce

Reproduce by following the instructions on the README (unsure how to type that without seeming sarcastic! apologies.)
I've added them here as well:

#### Activity: Update base.css
1. Create a new branch off of the main branch and change the body CSS declaration in base.css to match what is below. This will set the page background to black.
```
body {
    background-color: black;
}
```
2. Open a pull request with release-v1.0 as the base branch, and your new branch as the compare branch.
3. Fill in the pull request template to describe your changes.
4. Click Create pull request.

#### Activity: Merge the pull request
1. Click Merge pull request, and delete your branch.
2. Wait about 20 seconds then refresh this page (the one you're following instructions from). [GitHub Actions](https://docs.github.com/en/actions) will automatically update to the next step.

> I cannot produce screenshot as README/instructions did not update when refreshing page.

### Additional context

I'm new so my first thought was I made an error in following the instructions. I started over by deleting the cloned repo from my account, returned to GitHub Skills, and restarted the course. I ran into the same issue -- the README/instructions did not update to step 3.  Just to be sure, I waited another 2-3 minutes and refreshed the page again. Still not updating.

Thanks in advance! 

By the way, the **Skills courses are phenomenal** and have helped me learn many skills this week, including using markdown like I've applied in this post.

**Comment by hectorsector** [comment]
Thanks for the report @m-den-01A! Step 2 is looking for a new pull request set up specifically with `release-v1.0` as the base branch. I took a peek at your repository and see that the [PR you created](https://github.com/m-den-01A/skills-release-based-workflow/pull/3) has `main` as the base branch. It's easy to miss this detail but if you retry the course with `release-v1.0` as the base branch it should work. The part of the instructions that are relevant here are:

2. Open a pull request with **release-v1.0 as the base branch**, and your new branch as the compare branch.

If you still have trouble, feel to comment/reopen this issue.
